name: CI

on: [push]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint & Terraform validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4
        with: 
          terraform_version: "1.15.3"

      - name: Terraform validation
        working-directory: infra
        run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate -no-color
