name: CI
run-name: Triggered by ${{ github.actor }}

on: [push]

permissions:
  contents: read

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Terraform format check
        working-directory: infra
        run: |
          terraform init -backend=false
          terraform fmt -check